---
- name: Create .aws in root directory
  file:
    path: /root/.aws
    state: directory
    owner: "{{ credential.user }}"
    group: "{{ credential.user }}"
    mode: 0755
  when: credential.user == 'root'
  tags:
    - s3copy
    - webserver

- name: Check .aws in root directory
  stat:
    path: /root/.aws
  register: aws_dir_in_root
  when: credential.user == 'root'
  tags:
    - s3copy
    - webserver

- name: Create .aws in home directory
  file:
    path: "/home/{{ credential.user }}/.aws"
    state: directory
    owner: "{{ credential.user }}"
    group: "{{ credential.user }}"
    mode: 0755
  when: not credential.user == 'root'
  tags:
    - s3copy
    - webserver

- name: Check .aws in home directory
  stat:
    path: "/home/{{ credential.user }}/.aws"
  register: aws_dir_in_user
  when: not credential.user == 'root'
  tags:
    - s3copy
    - webserver

- name: Copy AWS cli creadentials setting in root
  copy:
    content: "{{ credential.content }}"
    dest: /root/.aws/credentials
    owner: "{{ credential.user }}"
    group: "{{ credential.user }}"
    mode: 0600
  when:
    - credential.user == 'root'
    - aws_dir_in_root.stat.exists
  tags:
    - s3copy
    - webserver

- name: Copy AWS cli creadentials setting in home directory
  copy:
    content: "{{ credential.content }}"
    dest: "/home/{{ credential.user }}/.aws/credentials"
    owner: "{{ credential.user }}"
    group: "{{ credential.user }}"
    mode: 0600
  when:
    - not credential.user == 'root'
    - aws_dir_in_user.stat.exists
  tags:
    - s3copy
    - webserver
